# Site settings
title: 柳伟卫/老卫/Way Lau's Personal Site - 关注编程、系统架构、性能优化
name: 柳伟卫/老卫/Way Lau's Personal Site
url: "https://waylau.com"
email: waylau521@gmail.com
description: 柳伟卫/老卫/Way Lau's Personal Site - 关注编程、系统架构、性能优化 | waylau.com
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: waylau521  # Twitter ID
github_username:  waylau # Github ID
weibo_username: waylau521  # Weibo ID
facebook_username: waylau521  # Facebook ID
#changyan_appid: cysJiEpFq # 畅言 appid
baidushare_id: 89860593 #  百度分享 ID
baidutongji_id: 28cf5fa48a599e39c5cc760931de942f # 百度统计 ID
#google-analytics_id: UA-50593531-1  # Google Analytics ID
rss_url: "/feed.xml"  # RSS 订阅 URL
logo_image: "/images/waylau_181_181.jpg"  # LOGO 图片地址
# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge   # pygments
permalink: /:title/
paginate: 38
paginate_path: page/:num
encoding: bom|utf-8
